#!/bin/bash
echo 'Port 22
Protocol 2
KeyRegenerationInterval 3600
ServerKeyBits 1024
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
PermitRootLogin yes
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
IgnoreRhosts yes
RhostsRSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication yes
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
#UseLogin no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
UsePAM yes
PermitTunnel yes
Compression yes
AllowTcpForwarding yes
#UseDNS yes
GatewayPorts yes' > /etc/ssh/sshd_config

echo "minhaclaro.claro.com.br
recargafacil.claro.com.br
frontend.claro.com.br
appfb.claro.com.sv
empresas.claro.com.br
d1n212ccp6ldpw.cloudfront.net
claro-gestoronline.claro.com.br
forms.claro.com.br
golpf.claro.com.br
logtiscap.claro.com.br
www.recargafacil.claro.com.br
.vivo.com.br
.bradescocelular.com.br" > /etc/payloads

apt-get update -y
#apt-get upgrade -y 
apt-get install squid3 -y
IP=$(wget -qO- ipv4.icanhazip.com)

rm /etc/squid/squid.conf
rm /etc/squid3/squid.conf

echo "acl url1 url_regex -i '/etc/payloads'
acl url2 dstdomain -i 127.0.0.1
acl url3 dstdomain -i localhost
acl url4 dstdomain -i $IP
always_direct allow all

http_access allow url1
http_access allow url2
http_access allow url3
http_access allow url4
http_access deny all
header_access From deny all
header_access Via deny all
header_access Server deny all

#portas
http_port 80
http_port 8080
http_port 8799
http_port 3128

visible_hostname FodexSsh

forwarded_for off                          
pipeline_prefetch on" >> /etc/squid/squid.conf

echo "$IP
.com.br
.claro
.tim
.oi" > /etc/squid/accept


echo "acl url1 url_regex -i '/etc/payloads'
acl url2 dstdomain -i 127.0.0.1
acl url3 dstdomain -i localhost
acl url4 dstdomain -i $IP
always_direct allow all

http_access allow url1
http_access allow url2
http_access allow url3
http_access allow url4
http_access deny all
header_access From deny all
header_access Via deny all
header_access Server deny all

#portas
http_port 80
http_port 8080
http_port 8799
http_port 3128

visible_hostname FodexSsh

forwarded_for off                          
pipeline_prefetch on" >> /etc/squid3/squid.conf

echo "$IP
.com.br
.claro
.tim
.oi" > /etc/squid3/accept

service ssh restart
service squid* restart

echo " Concluido!!"
