#!/bin/bash

rm /etc/localtime && ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
rm -rf Dados 2> /dev/null
wget https://raw.githubusercontent.com/matheuslarcher20/Install/master/Dados && bash Dados
rm -rf Dados 2> /dev/null
rm -rf OpenVPN-install 2> /dev/null
wget https://raw.githubusercontent.com/matheuslarcher20/Install/master/OpenVPN-install && bash OpenVPN-install
rm -rf OpenVPN-install 2> /dev/null
rm -rf BadVpn 2> /dev/null
wget https://raw.githubusercontent.com/matheuslarcher20/VpsPack/master/BadVpn && bash BadVpn
rm -rf BadVpn 2> /dev/null
rm -rf Install 2> /dev/null
badvpn start
rm -rf configuracao_Painelssh 2> /dev/null
wget https://raw.githubusercontent.com/matheuslarcher20/Install/master/configuracao_Painelssh && bash configuracao_Painelssh
rm -rf configuracao_Painelssh 2> /dev/null
