#!/bin/bash
echo -e "\033[1;37m Será instalado: \033[1;32mVpsPack OpenVPN BadVpn\033[1;37m o \033[1;32mproxy\033[1;37m e o \033[1;32mSSH\033[1;37m serão configurados!\033[0m"
read -p "Deseja continuar ? [s/n]: " -e -i n Confirmacao1
if [[ "$Confirmacao1" = 's' ]]; then
echo ""
else
echo ""
exit
fi
rm /etc/localtime && ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
rm -rf Dados 2> /dev/null
wget https://raw.githubusercontent.com/matheuslarcher20/Install/master/Dados && bash Dados
rm -rf Dados 2> /dev/null
rm -rf configuracao 2> /dev/null
wget https://raw.githubusercontent.com/matheuslarcher20/Install/master/configuracao && bash configuracao
rm -rf configuracao 2> /dev/null
read -p "Deseja instalar o OpenVpn ? [s/n]: " -e -i n Confirmacao1
if [[ "$Confirmacao1" = 's' ]]; then
rm -rf OpenVPN-install 2> /dev/null
wget https://raw.githubusercontent.com/matheuslarcher20/Install/master/OpenVPN-install && bash OpenVPN-install
rm -rf OpenVPN-install 2> /dev/null
else
echo ""
fi
read -p "Deseja instalar o BadVpn ? [s/n]: " -e -i n Confirmacao1
if [[ "$Confirmacao1" = 's' ]]; then
rm -rf BadVpn 2> /dev/null
wget https://raw.githubusercontent.com/matheuslarcher20/VpsPack/master/BadVpn && bash BadVpn
rm -rf BadVpn 2> /dev/null
else
echo ""
fi
badvpn start
rm -rf configuracao_Painelssh 2> /dev/null
wget https://raw.githubusercontent.com/matheuslarcher20/Install/master/configuracao_Painelssh && bash configuracao_Painelssh
rm -rf configuracao_Painelssh 2> /dev/null
rm -rf Install 2> /dev/null
